//! Terminal display width measurement.
//!
//! Terminal cells are not Unicode scalar values: CJK ideographs and most
//! emoji occupy two columns, while combining marks and variation selectors
//! occupy none. This module exposes true column width for frame layout.
//!
//! The range tables are generated by `tools/gen_width_tables.py`.

mod measure;
mod wide_astral;
mod wide_bmp;
mod zero_high;
mod zero_low;

pub(super) use measure::char_width;

#[cfg(test)]
mod partition_tests;
#[cfg(test)]
mod table_tests;
#[cfg(test)]
mod tests;
