//! WebGL constants installed on context objects.

use super::webgl_constants as c;

pub(super) const ALL: &[(&str, u32)] = &[
    ("VENDOR", c::VENDOR),
    ("RENDERER", c::RENDERER),
    ("VERSION", c::VERSION),
    ("SHADING_LANGUAGE_VERSION", c::SHADING_LANGUAGE_VERSION),
    ("MAX_TEXTURE_SIZE", c::MAX_TEXTURE_SIZE),
    ("MAX_VIEWPORT_DIMS", c::MAX_VIEWPORT_DIMS),
    ("VIEWPORT", c::VIEWPORT),
    ("COLOR_CLEAR_VALUE", c::COLOR_CLEAR_VALUE),
    ("DEPTH_CLEAR_VALUE", c::DEPTH_CLEAR_VALUE),
    ("STENCIL_CLEAR_VALUE", c::STENCIL_CLEAR_VALUE),
    ("SCISSOR_BOX", c::SCISSOR_BOX),
    ("SCISSOR_TEST", c::SCISSOR_TEST),
    ("COLOR_WRITEMASK", c::COLOR_WRITEMASK),
    ("ALIASED_LINE_WIDTH_RANGE", c::ALIASED_LINE_WIDTH_RANGE),
    ("ALIASED_POINT_SIZE_RANGE", c::ALIASED_POINT_SIZE_RANGE),
    ("MAX_VERTEX_ATTRIBS", c::MAX_VERTEX_ATTRIBS),
    (
        "MAX_COMBINED_TEXTURE_IMAGE_UNITS",
        c::MAX_COMBINED_TEXTURE_IMAGE_UNITS,
    ),
    ("MAX_TEXTURE_IMAGE_UNITS", c::MAX_TEXTURE_IMAGE_UNITS),
    (
        "MAX_VERTEX_TEXTURE_IMAGE_UNITS",
        c::MAX_VERTEX_TEXTURE_IMAGE_UNITS,
    ),
    ("COLOR_BUFFER_BIT", c::COLOR_BUFFER_BIT),
    ("DEPTH_BUFFER_BIT", c::DEPTH_BUFFER_BIT),
    ("STENCIL_BUFFER_BIT", c::STENCIL_BUFFER_BIT),
    ("RGBA", c::RGBA),
    ("UNSIGNED_BYTE", c::UNSIGNED_BYTE),
    ("NO_ERROR", c::NO_ERROR),
    ("INVALID_ENUM", c::INVALID_ENUM),
    ("INVALID_VALUE", c::INVALID_VALUE),
    ("INVALID_OPERATION", c::INVALID_OPERATION),
    ("OUT_OF_MEMORY", c::OUT_OF_MEMORY),
];
