#!/usr/bin/env python3
"""Regenerate the TetherScript terminal width tables from Unicode data.

Emits the Rust range tables consumed by `src/tui/width/`. Run this when
bumping to a newer Unicode version, then commit the regenerated files:

    python3 tools/gen_width_tables.py

Width rules follow the conventional terminal (wcwidth) model:
  * East Asian Wide (W) and Fullwidth (F) -> 2 columns
  * Nonspacing/enclosing marks (Mn, Me) and format chars (Cf) -> 0 columns
  * everything else -> 1 column
"""

import unicodedata
from pathlib import Path

PER_LINE = 4
ROOT = Path(__file__).resolve().parent.parent / "src" / "tui" / "width"


def ranges(predicate):
    """Collapse matching codepoints into sorted, non-overlapping ranges."""
    out = []
    for cp in range(0x110000):
        if predicate(cp):
            if out and cp == out[-1][1] + 1:
                out[-1][1] = cp
            else:
                out.append([cp, cp])
    return out


def is_wide(cp):
    return unicodedata.east_asian_width(chr(cp)) in ("W", "F")


def is_zero(cp):
    return unicodedata.category(chr(cp)) in ("Mn", "Me", "Cf")


def is_wide_only(cp):
    """Wide takes effect only when the codepoint is not zero-width.

    A few codepoints are both East Asian Wide and combining marks
    (for example U+302A..U+302D, the Han tone marks). Those attach to a
    preceding glyph and consume no cells, so zero-width wins. Excluding
    them here keeps the emitted tables disjoint.
    """
    return is_wide(cp) and not is_zero(cp)


def fmt(rows, width):
    """Format ranges as Rust tuple literals, PER_LINE per source line."""
    lines = []
    for i in range(0, len(rows), PER_LINE):
        chunk = rows[i : i + PER_LINE]
        cells = ", ".join(f"(0x{lo:0{width}X}, 0x{hi:0{width}X})" for lo, hi in chunk)
        lines.append(f"    {cells},")
    return "\n".join(lines)


def emit(path, name, doc, rows, width):
    body = f"""//! {doc}
//!
//! Generated by `tools/gen_width_tables.py` from Unicode
//! {unicodedata.unidata_version}. Do not edit by hand.

/// {doc}
#[rustfmt::skip]
pub(super) const {name}: &[(u32, u32)] = &[
{fmt(rows, width)}
];
"""
    path.write_text(body, encoding="utf-8")
    print(f"{path.name}: {len(rows)} ranges")


def main():
    wide = ranges(is_wide_only)
    zero = ranges(is_zero)
    bmp = [r for r in wide if r[0] < 0x10000]
    astral = [r for r in wide if r[0] >= 0x10000]
    half = (len(zero) + 1) // 2
    split = zero[half][0]

    emit(
        ROOT / "wide_bmp.rs",
        "WIDE_BMP",
        "East Asian Wide/Fullwidth ranges in the Basic Multilingual Plane.",
        bmp,
        4,
    )
    emit(
        ROOT / "wide_astral.rs",
        "WIDE_ASTRAL",
        "East Asian Wide/Fullwidth ranges above the Basic Multilingual Plane.",
        astral,
        5,
    )
    emit(
        ROOT / "zero_low.rs",
        "ZERO_LOW",
        f"Zero-width combining and format ranges below U+{split:04X}.",
        zero[:half],
        4,
    )
    emit(
        ROOT / "zero_high.rs",
        "ZERO_HIGH",
        f"Zero-width combining and format ranges from U+{split:04X} up.",
        zero[half:],
        4,
    )


if __name__ == "__main__":
    main()
