//! DOM and data constructors exposed as unqualified globals.

pub(super) const ALL: &[&str] = &[
    "Event",
    "CustomEvent",
    "MouseEvent",
    "KeyboardEvent",
    "InputEvent",
    "SubmitEvent",
    "FocusEvent",
    "PointerEvent",
    "WheelEvent",
    "DOMMatrix",
    "DOMMatrixReadOnly",
    "ImageData",
    "URL",
    "URLPattern",
    "URLSearchParams",
    "AbortController",
    "Request",
    "Response",
    "Headers",
    "DOMParser",
    "XMLSerializer",
    "Node",
    "Element",
    "HTMLElement",
    "Document",
    "DocumentFragment",
    "NodeFilter",
];
