//! JavaScript data, worker, and utility globals.

pub(super) const ALL: &[&str] = &[
    "atob",
    "btoa",
    "Uint8Array",
    "Uint8ClampedArray",
    "Uint32Array",
    "Uint16Array",
    "Int32Array",
    "Float32Array",
    "ArrayBuffer",
    "SharedArrayBuffer",
    "TextEncoder",
    "TextDecoder",
    "Blob",
    "File",
    "FormData",
    "FileReader",
    "structuredClone",
    "crypto",
    "trustedTypes",
    "CSS",
    "CSSStyleSheet",
    "customElements",
    "MessageChannel",
    "BroadcastChannel",
    "Worker",
    "registerWorkerScript",
];
