//! Browser service, observer, viewport, and layout globals.

pub(super) const ALL: &[&str] = &[
    "getComputedStyle",
    "getBoundingClientRect",
    "getAccessibilityTree",
    "fetch",
    "XMLHttpRequest",
    "WebSocket",
    "EventSource",
    "MutationObserver",
    "IntersectionObserver",
    "ResizeObserver",
    "ReportingObserver",
    "performance",
    "scheduler",
    "requestIdleCallback",
    "cancelIdleCallback",
    "PerformanceObserver",
    "matchMedia",
    "screen",
    "visualViewport",
    "innerWidth",
    "innerHeight",
    "devicePixelRatio",
    "scrollX",
    "scrollY",
    "pageXOffset",
    "pageYOffset",
];
