name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt

      - run: bash ./check_file_limits.sh
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
      - run: cargo test --test browser_wpt_like
      - run: cargo test
      - run: cargo test --doc
      - run: RUSTDOCFLAGS="-D warnings" cargo doc --no-deps
      - run: cargo package
